name: IITM Verification Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-code: true
    runs-on: ubuntu-latest
    steps:
      - name: 24f2006763@ds.study.iitm.ac.in
        run: echo "Hello, world!"
